#!/bin/bash
set -e

docker run -it \
    --name gluu \
    --hostname sso \
    -v `pwd`/setup.properties:/install/community-edition-setup/setup.properties.last \
    -v `pwd`/../data/opendj/db:/opt/opendj/db \
    quay.io/gluu/gluu:2.4.4.2 gluu_setup

docker commit gluu gluu

docker rm gluu